version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: pag-bank
    container_name: pag-bank-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - pag-bank

  db:
    image: mysql:5.7
    container_name: pag-bank-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: pagbankdb
#      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: userdb
#      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_PASSWORD: userdb
#      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_USER: userdb
#      MYSQL_USER: "${DB_USERNAME}"
    ports:
        - "${DB_PORT}:3306"
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - ./docker-compose/mysql/db:/var/lib/mysql
    networks:
      - pag-bank

  nginx:
    image: nginx:alpine
    container_name: pag-bank-nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - pag-bank

networks:
  pag-bank:
    driver: bridge
